from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from models import db, Article
#from ai_model import TextGenerator
import os
import datetime

app = Flask(__name__)
app.config.from_object('config.Config')
CORS(app)
db.init_app(app)

with app.app_context():
    db.create_all()

slack_token = os.getenv('SLACK_BOT_TOKEN')
client = WebClient(token=slack_token)

#text_generator = TextGenerator()

def save_text_to_file(text, prompt):
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{prompt[:50]}_{timestamp}.txt"
    filepath = os.path.join('generated_texts', filename)
    
    if not os.path.exists('generated_texts'):
        os.makedirs('generated_texts')
        
    with open(filepath, 'w') as file:
        file.write(text)
    return filename

@app.route('/generate', methods=['POST'])
def generate():
    data = request.json
    prompt = data.get('prompt')
    intensity = data.get('intensity')
    
    # Generate text using the AI model
    # max_length = 50 + intensity * 10
    # generated_text = text_generator.generate_text(prompt, max_length)
    generated_text = "This will be an article generated by AI that uses the prompt: {}".format(prompt) 
    
    # Save to database
    article = Article(prompt=prompt, intensity=intensity, generated_text=generated_text)
    db.session.add(article)
    db.session.commit()

    # Save generated text to a file
    filename = save_text_to_file(generated_text, prompt)
    
    # Send message to Slack channel
    try:
        response = client.chat_postMessage(
            channel='#general',  # Change to your Slack channel
            text=generated_text
        )
    except SlackApiError as e:
        return jsonify({'error': str(e.response['error'])}), 500

    return jsonify({'article': generated_text, 'file': filename})

@app.route('/download/<filename>', methods=['GET'])
def download_file(filename):
    return send_from_directory('generated_texts', filename)

@app.route('/articles', methods=['GET'])
def get_articles():
    articles = Article.query.all()
    articles_list = [
        {
            'id': article.id,
            'prompt': article.prompt,
            'intensity': article.intensity,
            'generated_text': article.generated_text,
            'timestamp': article.timestamp
        }
        for article in articles
    ]
    return jsonify(articles_list)

if __name__ == '__main__':
    app.run(debug=True)

